---
title: "First Knit"
author: "Wailana Reyes"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  
I attended and graduated from Learn4Life this past summer. When comparing English and Math, Math seems like the easier choice. I did best in Math.
     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  
  I have an HP computer at home. I would rate myself a 5 based on my knowledge of computers, I am confident in using basic applications. I have good internet connection at home.
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  
  
 I prefer to be called by my first name, Wailana. I'm also open to nicknames, whatever is easy for people to remember.




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  
   I would like to become a Psychiatrist, as well as serve time in the Military (specifically the Air Force). To get to my goal in psychiatry, I would need to continue taking Psychology Courses or maybe even Chemistry or Biology, all of these would be of great interest to me. At AVC, I am trying to obtain my Associates in Psychology.
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  
   
   I have never been to any foreign countries, but I would love to visit Europe and Asia. I also have never been enlisted in the military. If I were to get drafted I would choose to join the Air Force because they are the last to get sent to the field and are generally more "brain work" than physical work.
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
   
   
 






  




